### ISSUE TITLE
Minor: "Supporting Quotes" nav item missing on quotes page

### ISSUE THREAD

**Issue by luciddreamz** [openshift/commons.openshift.org#10]
The "Supporting Quotes" navigation item is missing on the [quotes page](http://icarus.usersys.redhat.com/quotes.html). This is a minor issue, but the behavior is inconsistent with other pages on the site like the [events page](http://icarus.usersys.redhat.com/briefings.html).

**Comment by Nick-Harvey** [comment]
fixed thanks for reporting
