### ISSUE TITLE
Event calandar hangs when switching dates

### ISSUE THREAD

**Issue by luciddreamz** [openshift/commons.openshift.org#11]
Changing the date on the [event calendar](http://icarus.usersys.redhat.com/briefings.html) (using the forward/back arrows) causes the calendar to hang indefinitely.

![using back arrow](https://cloud.githubusercontent.com/assets/928421/6349997/011838d6-bbfe-11e4-97b0-435a1f05ba4d.png)

![using forward arrow](https://cloud.githubusercontent.com/assets/928421/6350004/1035754a-bbfe-11e4-8bd0-ff5fe715d9c7.png)

**Comment by Nick-Harvey** [comment]
Looks like this might be an issue with Time.ly plugin 

Uncaught TypeError: undefined is not a function      live-timely-objzoywz.time.ly/wp-content/plugins/all-in-one-event-calendar-extended-views/public/js/pages/extended_views.js:62 Uncaught TypeError: undefined is not a function

Uncaught TypeError: undefined is not a functionextended_views.js:62 sextended_views.js:62 aextended_views.js:62 oextended_views.js:62 (anonymous function)?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:51 timely.define.jQuery.event.dispatch?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:51 timely.define.jQuery.event.add.m.handle?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:51 timely.define.jQuery.event.trigger?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:51 (anonymous function)?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:51 timely.define.jQuery.extend.each?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:51 timely.define.jQuery.fn.jQuery.each?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:51 timely.define.jQuery.fn.extend.triggerextended_views.js:62 (anonymous function)?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:15 r.execCb?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:15 n.check?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:15 n.enable?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:15 n.init?ai1ec_super_widget=true&ai1ec_sw_version=1.0.9:15 (anonymous function)

I'm going to try and open a bug with them.

**Comment by Nick-Harvey** [comment]
case opened
