### ISSUE TITLE
Add Pega Systems to Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#110]
url: http://www.pega.com
logo: jpeg emailed to edirsh and here is a png http://www.pega.com/profiles/pegasystems/themes/custom/pegas/logo.png

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/0004e767daea9c141d2f48e85c05b3ed1151ad81
