### ISSUE TITLE
Add DreamFactory to Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#111]
url: http://www.dreamfactory.com
logo: http://cdn2.hubspot.net/hub/247169/file-2465293383-png/images/df-logo-nav-reversed_2x.png

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/0004e767daea9c141d2f48e85c05b3ed1151ad81
