### ISSUE TITLE
Unofficial OpenShift logo used on quotes page

### ISSUE THREAD

**Issue by luciddreamz** [openshift/commons.openshift.org#12]
The OpenShift logo [used on the quotes page](http://icarus.usersys.redhat.com/quotes.html#OpenShift) is not an official OpenShift logo. Please update with an actual brand provided logo (provided below).

![not the official OpenShift logo](https://cloud.githubusercontent.com/assets/928421/6350069/7eab1980-bbfe-11e4-9ec6-c4f42ee9b6fd.png)

![openshift_vertical_rgb](https://cloud.githubusercontent.com/assets/928421/6350116/fd7fbe14-bbfe-11e4-8d93-bc41d021b6a9.png)

**Comment by Nick-Harvey** [comment]
fixed thanks for reporting and providing the logo
