### ISSUE TITLE
Add DataDog to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#125]
url: http://www.datadoghq.com

logo: http://m3xg3lob3p2dp7jl2yeyci13.wpengine.netdna-cdn.com/wp-content/themes/datadog/assets/images/datadog-logo-purple.gif

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/92f20848b6a18d18981984656031fb2c3e59a94b
