### ISSUE TITLE
Add Sapho to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#126]
url: http://www.sapho.com
logo: http://3iia8p3o8lbg2ds0b45fsszk.wpengine.netdna-cdn.com/wp-content/uploads/2014/10/sapho-logo-transparent-30.png

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/92f20848b6a18d18981984656031fb2c3e59a94b
