### ISSUE TITLE
No confirmation page or message for "Join Now" form on homepage

### ISSUE THREAD

**Issue by luciddreamz** [openshift/commons.openshift.org#13]
The thank-you page for submitting the "Join Now" form on [the homepage](http://icarus.usersys.redhat.com/index.html) provides no feedback to users after submitting the form. Users are simply returned to the homepage with a blank form. For reference, no confirmation email is sent upon successful submission of the form either.

The thank-you page for the form is shown below:

![form thank-you page](https://cloud.githubusercontent.com/assets/928421/6350158/61b4868a-bbff-11e4-9302-f6012c98745f.png)

**Comment by Nick-Harvey** [comment]
Resolved. Thanks for pointing this out.
