### ISSUE TITLE
add UNC to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#130]
url: http://www.unc.edu
logo: https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/UNC_Chapel_Hill_Logo.svg/1280px-UNC_Chapel_Hill_Logo.svg.png

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/093a2bb31dcc5b21aa87f95f2b4e48a10073d0c6
