### ISSUE TITLE
Add Raiffeisen Informatik to Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#139]
url:http://www.raiffeiseninformatik.at/
logo: https://www.raiffeiseninformatik.at/fileadmin/templates/img/logo.gif

**Comment by EmilyDirsh** [comment]
Closed in https://github.com/openshift/commons.openshift.org/commit/5857d9b4bdaebb20c0add1d6372fcc5c9d6b13e5
