### ISSUE TITLE
OpenShift 3 or OpenShift V3 or OpenShift v3? Inconsistent usage...

### ISSUE THREAD

**Issue by luciddreamz** [openshift/commons.openshift.org#14]
On the [sig page for OpenShift 3](http://icarus.usersys.redhat.com/sig/Openshift3.html) the naming convention for the upcoming version of OpenShift is used inconsistently.

![OpenShift 3 vs OpenShift V3](https://cloud.githubusercontent.com/assets/928421/6350226/e8c89c1a-bbff-11e4-9d99-bf12831dd986.png)

![OpenShift v3](https://cloud.githubusercontent.com/assets/928421/6350260/31e9ffa6-bc00-11e4-961e-1f041a30f5df.png)

**Comment by Nick-Harvey** [comment]
fixed!  thanks for reporting this one. I totally forgot about this
