### ISSUE TITLE
add stamplay to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#140]
url: https://stamplay.com

url: http://apidaysberlin2015.apistrat.com/wp-content/uploads/2015/04/Stamplay_logo_squared.png

**Comment by EmilyDirsh** [comment]
Closed in https://github.com/openshift/commons.openshift.org/commit/5857d9b4bdaebb20c0add1d6372fcc5c9d6b13e5
