### ISSUE TITLE
add StackRox to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#143]
url: http://stackrox.com/
logo:  https://d1qb2nb5cznatu.cloudfront.net/startups/i/578904-b5d09939c41156f7c4cc15543617569d-medium_jpg.jpg?buster=1427859486

**Comment by EmilyDirsh** [comment]
Closed in https://github.com/openshift/commons.openshift.org/commit/5857d9b4bdaebb20c0add1d6372fcc5c9d6b13e5
