### ISSUE TITLE
add UOL to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#145]
url: http://www.uol.com.br/
logo: http://img3.wikia.nocookie.net/__cb20130406215506/logopedia/images/thumb/5/55/3434.jpg/200px-3434.webp

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/1fb99422da8bf871fe95199a162f09b48be18056
