### ISSUE TITLE
add cloudsoft to openshift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#146]
url: http://www.cloudsoftcorp.com/
logo: http://developer.cloudsoftcorp.com/download/eclipse/update-e36/plugins/com.cloudsoftcorp.monterey.studio.common_3.2.0.v20110502-351-10779/content/images/cloudsoft-logo-big.png

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/1fb99422da8bf871fe95199a162f09b48be18056
