### ISSUE TITLE
OpenShift Ops and OpenShift 3 pages missing logo in header

### ISSUE THREAD

**Issue by luciddreamz** [openshift/commons.openshift.org#15]
The OpenShift Ops and OpenShift 3 pages are missing the OpenShift logo in the header. Other stand-alone pages have the logo - I'd say just add it for consistency.

![supporting quotes w/ logo](https://cloud.githubusercontent.com/assets/928421/6350310/a6f83ede-bc00-11e4-8405-3e6dfe92ff9c.png)

![OpenShift ops w/out logo](https://cloud.githubusercontent.com/assets/928421/6350314/b0d5d786-bc00-11e4-9160-4c37381bc392.png)

![OpenShift 3 w/out logo](https://cloud.githubusercontent.com/assets/928421/6350320/bbd92f8e-bc00-11e4-8456-d443c16087d7.png)

**Comment by EmilyDirsh** [comment]
Fixed in https://github.com/openshift/commons.openshift.org/commit/a3fdca65b3fc29a0aef8d1da0e080f6c388a019e
