### ISSUE TITLE
add Kaazing to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#152]
url: kaazing.com
logo: https://s3-us-west-2.amazonaws.com/www.kaazing.com/wordpress/wp-content/uploads/2013/05/Kaazing_logo.png

**Comment by EmilyDirsh** [comment]
Added in Added in https://github.com/openshift/commons.openshift.org/commit/0cd48c73815f76be754be6e83748d758e58b7971
