### ISSUE TITLE
adding crypteron to openshift commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#153]
url: crypteron.com
logo: http://cdn.crypteron.com/press/CrypteronPressKit.zip

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/0cd48c73815f76be754be6e83748d758e58b7971

**Comment by sidshetye** [comment]
Could we change to the "CrypteronBannerDark_3600px.png" banners provided inside the press kit at http://cdn.crypteron.com/press/CrypteronPressKit.zip?

That would convey the brand more effectively than the current standalone icon.
