### ISSUE TITLE
No confirmation page or message for "Special Interest" forms

### ISSUE THREAD

**Issue by luciddreamz** [openshift/commons.openshift.org#16]
The special interest group forms for [OpenShift Ops](http://icarus.usersys.redhat.com/sig/Operations.html) and [OpenShift 3](http://icarus.usersys.redhat.com/sig/Openshift3.html) provide no confirmation page or message for form submissions.

The thank-you screen for submitting the forms are shown below:

![screen shot 2015-02-24 at 8 38 26 am](https://cloud.githubusercontent.com/assets/928421/6350348/1f82dbe8-bc01-11e4-9ad7-c3eefa7f21af.png)

![screen shot 2015-02-24 at 8 41 30 am](https://cloud.githubusercontent.com/assets/928421/6350351/22f14814-bc01-11e4-999d-162ead62eed6.png)

**Comment by Nick-Harvey** [comment]
Resolved. Thanks for pointing this out.
