### ISSUE TITLE
Briefings Calendar Pops not rendering correctly

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#163]
When anyone clicks on a item on the Calendar the pop-up for the details is getting clobbered.

 the time.ly support folks say that the fix is as follows:

1. Please add the following code into your site css, it should fix this css conflict:

#ai1ec-event-modal .clearfix

{

width: 100%;

}

**Comment by EmilyDirsh** [comment]
Fixed in https://github.com/openshift/commons.openshift.org/commit/2f28235be00e96fdedb57d4a66e43084aca6450f
