### ISSUE TITLE
Missing favicon on OpenShift Operations and OpenShift 3 pages

### ISSUE THREAD

**Issue by luciddreamz** [openshift/commons.openshift.org#17]
The [OpenShift Ops](http://icarus.usersys.redhat.com/sig/Operations.html) and [OpenShift 3](http://icarus.usersys.redhat.com/sig/Openshift3.html) pages are missing a favicon:

![missing favicon](https://cloud.githubusercontent.com/assets/928421/6350417/a41c0abe-bc01-11e4-8dc8-aa4c35bc1386.png)

**Comment by EmilyDirsh** [comment]
This was fixed at some point.
