### ISSUE TITLE
99clouds to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#170]
url: http://99cloud.net
logo: https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTcOCcL4RqDhzhhEN3HHQ88_wQHs9dQ1auRUc-DO3UtpZDuMfB9

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/1fc9bf870b2f2701021bdbf6659ad2b2269fb8d7
