### ISSUE TITLE
add Eupraxia Labs to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#186]
url: site launching 1/18/2016 
new logo: under-development will be emailed shortly

**Comment by jiri-fiala** [comment]
Eupraxia logo scaled to 120px width: 
![eupraxia](https://cloud.githubusercontent.com/assets/14938461/12951607/61b9fcc2-d013-11e5-9542-4f200ce845ad.png)

**Comment by shubheksha** [comment]
I am a beginner & I'd like to work on this. From what I understand, I need to add this to the list of already existing 'Commons Participants'? Please correct me if I am wrong.

**Comment by jsvgoncalves** [comment]
@shubheksha Thanks for your interest in contributing. This issue is currently pending and waiting for Eupraxia; I'll notify you as soon as we have any news.

**Comment by shubheksha** [comment]
@jsvgoncalves, okay - I've made all the other changes. Will update the URL as soon as it's available and submit a PR.

**Comment by shubheksha** [comment]
@jsvgoncalves, any update?

**Comment by jiri-fiala** [comment]
Updates will be posted here, when ready and the "pending" label removed then. (It seems the site is not yet launched.)

**Comment by jiri-fiala** [comment]
@dmueller2001, any updates on the Eupraxia Labs website?

**Comment by dmueller2001** [comment]
![eupraxia](https://cloud.githubusercontent.com/assets/4029488/14726685/0814ab7e-07d9-11e6-89c7-2b89f06d49e2.png)

@jiri-fiala use this logo for eupraxia for now; and leave the link to their site off; I will add the link when they launch their new site later this month.

**Comment by developercorey** [comment]
can this issue be closed? has it been completed?

**Comment by jsvgoncalves** [comment]
@developercorey we still don't have the link for their website. waiting on @dmueller2001

**Comment by dmueller2001** [comment]
still no website launched..stay tuned

On Tue, Apr 26, 2016 at 10:12 AM, João Gonçalves <notifications@github.com>
wrote:

> @developercorey <https://github.com/developercorey> we still don't have
> the link for their website. waiting on @dmueller2001
> <https://github.com/dmueller2001>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/commons.openshift.org/issues/186#issuecomment-214778379>
>



-- 
Kind Regards,

Diane Mueller
Director, Community Development
Red Hat OpenShift
@openshiftcommons

We have more in Common than you know, learn more at
http://commons.openshift.org

**Comment by coreydaley** [comment]
Please re-open this issue or create a new one when the website is ready.  Url has not been provided in 4+ months
