### ISSUE TITLE
Selecting the default option "Go to" in mobile navigation menu causes 404 error

### ISSUE THREAD

**Issue by luciddreamz** [openshift/commons.openshift.org#19]
Selecting the default option "Go to" in the mobile navigation menu causes the browser to navigate to [http://icarus.usersys.redhat.com/Go%20to](http://icarus.usersys.redhat.com/Go%20to). On a related note: the mobile menu could probably use some styling updates.

![mobile navigation menu](https://cloud.githubusercontent.com/assets/928421/6350496/60031092-bc02-11e4-9fda-0ab8462202ea.png)

**Comment by Nick-Harvey** [comment]
Fixed! Thanks for reporting this one. This was an interesting one to fix. Now the "Nav To" section always remains "active"
