### ISSUE TITLE
Amadeus logo stretched in Internet Explorer

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#20]
I got a call from Amadeus saying that their logo was looking weirdly stretched when viewed in Internet Explorer; I haven't got IE on any machine to test..

**Comment by EmilyDirsh** [comment]
This is most likely due to using SVG. I've converted it to a png in https://github.com/openshift/commons.openshift.org/commit/10765a154840cfdbd49294c907036f621c2dab34 - should fix the issue.
