### ISSUE TITLE
Add Cloudwerkstatt to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#207]
url:http://www.cloudwerkstatt.com/
logo: https://drive.google.com/a/redhat.com/file/d/0B-NzmustWNyPZXQ3Ny1tZEI5TzQ/

**Comment by jsvgoncalves** [comment]
@jiri-fiala

**Comment by dmueller2001** [comment]
the url: http://www.cloudwerkstatt.com/ is correct
the logo was mailed to @jsvgoncalves and @jiri-fiala
