### ISSUE TITLE
add boondoc.ca to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#208]
url: http://boondoc.ca 
logo: 
![logo_300](https://cloud.githubusercontent.com/assets/4029488/12930038/f6b35b64-cf2a-11e5-81c8-d9df4a94b38a.png)

**Comment by jsvgoncalves** [comment]
@jiri-fiala

**Comment by jiri-fiala** [comment]
Please update the issue; the URL provided leads to an empty page and the logo suggests it should go to http://www.cloudwerkstatt.com/

**Comment by jiri-fiala** [comment]
Boondoc logo, 120px wide:
![boondoc120](https://cloud.githubusercontent.com/assets/14938461/12972396/159cb09a-d0a5-11e5-9310-a17e7a4f8f03.png)

**Comment by dmueller2001** [comment]
Sorry for the confusion:

The boondoc.ca team would like us to point to  https://therounds.com  for now

@jiri-fiala @jsvgoncalves

**Comment by jsvgoncalves** [comment]
@dmueller2001 with which logo? boondoc or therounds?

**Comment by dmueller2001** [comment]
they want to use the boondoc logo with the therounds url

Diane
