### ISSUE TITLE
Title Tags Added Incorrectly (creating multiple <head> tags)

### ISSUE THREAD

**Issue by luciddreamz** [openshift/commons.openshift.org#21]
![multiple head tags](https://cloud.githubusercontent.com/assets/928421/6401694/2c9a77c0-bdd0-11e4-8a37-91e0d2d8b917.png)

**Comment by EmilyDirsh** [comment]
Fixed in https://github.com/openshift/commons.openshift.org/commit/fe470135f1c27471245eb4a09bcf56a31e0a5a65
