### ISSUE TITLE
 Add LSD Information Technology to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#210]
url: http://www.lsd.co.za/
logo: https://static.wixstatic.com/media/c71f7a_58b068d37edd4771a208432403963e1b.png/v1/fill/w_117,h_70,al_c,usm_0.66_1.00_0.01/c71f7a_58b068d37edd4771a208432403963e1b.png

need to figure out how to make a gray-scale version of logo from the site..i have also asked them for one as well

**Comment by jsvgoncalves** [comment]
@jiri-fiala
