### ISSUE TITLE
add pachyderm.io to Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#232]
url: http://www.pachyderm.io/ 
logo: still in transist

**Comment by jiri-fiala** [comment]
@dmueller2001, any update on the Pachyderm logo?
We can use their company name on a dark blue background (the same as they have on [their website](http://www.pachyderm.io/)), if that's suitable:
![selection_008](https://cloud.githubusercontent.com/assets/14938461/14522962/7804275a-0231-11e6-8bee-9ee92ee61fd2.png)

**Comment by dmueller2001** [comment]
@jiri-fiala yes, use the company name on a dark blue background and post
