### ISSUE TITLE
Commons Time.ly Calendar of Upcoming Briefings not appearing http/https issue

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#240]
I keep noticing the briefings calendar often doesn't show up on the
commons website.  After taking a closer look, it seems that the URL
being called is http not https and since commons.openshift.org is now
https most browsers are blocking it so I don't know if anyone is
seeing the upcoming briefings calendar.

I think the embedded widget just needs to be updated or edited.

@jiri-fiala @jsvgoncalves

**Comment by dmueller2001** [comment]
Widget needs to have "http://" changed to "//"

@jiri-fiala @jsvgoncalves 

below is the new snippet of code to add to the site. 

 <script class="ai1ec-widget-placeholder" data-widget="ai1ec_superwidget" data-action="posterboard">
            (function(){var d=document,s=d.createElement('script'),
            i='ai1ec-script';if(d.getElementById(i))return;s.async=1;
            s.id=i;s.src='//live-timely-objzoywz.time.ly/?ai1ec_js_widget';
            d.getElementsByTagName('head')[0].appendChild(s);})();
          </script>

**Comment by jsvgoncalves** [comment]
@dmueller2001 is there some text missing on your last post? Also, after we started looking into this we realised there were updates with 800be16bc9965f550a4e338abaaf11e605d69ea0. Is the issue fixed?
cc: @developercorey

**Comment by developercorey** [comment]
This issue has not been resolved, the "//" proposed fix did not resolve the issue.  It seems that even when using the https version of the src url, it is still trying to include non-https resources.

**Comment by dmueller2001** [comment]
*Heavy Sigh*, Yes this is still an open issue.

I have a incident report in with time.ly on the issues; let's give them to
the EOD today to get back with a solution before I start figuring out an
alternative approach to calendar listings..

Diane

On Tue, Mar 29, 2016 at 6:41 AM, Corey Daley <notifications@github.com>
wrote:

> This issue has not been resolved, the "//" proposed fix did not resolve
> the issue. It seems that even when using the https version of the src url,
> it is still trying to include non-https resources.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/commons.openshift.org/issues/240#issuecomment-202898312>
>



-- 
Kind Regards,

Diane Mueller
Director, Community Development
Red Hat OpenShift
@openshiftcommons

We have more in Common than you know, learn more at
http://commons.openshift.org

**Comment by dmueller2001** [comment]
Yahoo! Time.ly responded in a timely fashion and the issue appears to have been fixed. More details to follow.

**Comment by developercorey** [comment]
The calendar is showing up now, but the content it is serving still gives a "mixed secure/insecure content" warning in the browser.  Just an FYI

**Comment by dmueller2001** [comment]
hmmm...can you send me a screenshot of the content warning so I can forward
it to timely folks?

thanks

d

On Wed, Mar 30, 2016 at 9:51 AM, Corey Daley <notifications@github.com>
wrote:

> The calendar is showing up now, but the content it is serving still gives
> a "mixed secure/insecure content" warning in the browser. Just an FYI
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/commons.openshift.org/issues/240#issuecomment-203523175>
>



-- 
Kind Regards,

Diane Mueller
Director, Community Development
Red Hat OpenShift
@openshiftcommons

We have more in Common than you know, learn more at
http://commons.openshift.org

**Comment by developercorey** [comment]
Sure, 
Here you go.
<img width="408" alt="screenshot 2016-03-30 14 38 08" src="https://cloud.githubusercontent.com/assets/5060301/14153286/3b5e70d8-f685-11e5-86df-aaa54e3081ac.png">
<img width="1261" alt="screenshot 2016-03-30 14 39 15" src="https://cloud.githubusercontent.com/assets/5060301/14153287/3b602888-f685-11e5-819a-e48d9b5856b8.png">
