### ISSUE TITLE
Add codearte.io logo on OpenShift Commons 

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#241]
url: http://codearte.io/
logo: http://codearte.io/images/codearte_logo_transparent.png

@jiri-fiala @jsvgoncalves

**Comment by jiri-fiala** [comment]
Already added on Feb 18 in 06e35a3 by @jsvgoncalves.

**Comment by jsvgoncalves** [comment]
PR #219 closed issue #217 with commit 06e35a3 on Feb. 18.
