### ISSUE TITLE
add a .EDU SIG page with link to sign-up

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#246]
new page url: http://commons.openshift.org/sig/OpenshiftEDU.html

links added to http://commons.openshift.org/index.html#interests section of home page

update google spreadsheet-based form to start collecting email addresses

@jiri-fiala @jsvgoncalves

**Comment by jiri-fiala** [comment]
@dmueller2001, could you please specify the form and the content of this new page?

**Comment by dmueller2001** [comment]
Form/Style should mirror the existing SIG page  /sig/Openshiftv3.html

Content for link on index.html: 

'OpenShift .EDU' 

Content for beneath link on #interests section of index.html 

'Discuss, develop and disseminate best practices for administrating, managing and operating OpenShift in .EDU setting'

Content for http://commons.openshift.org/sig/OpenshiftEDU.html

'Join the OpenShift .EDU Special Interest Group'

Cut the section of the page entitled 'OpenShift 3 Commons Briefings' on the .edu sig landing page.

Copy the section of the page entitled 'OpenShift 3 Articles' onto the .edu sig landing page.

**Comment by jiri-fiala** [comment]
Pages are prepared, forms pending - waiting for access.

**Comment by jiri-fiala** [comment]
This can be previewed & tested at:
http://comm-jfiala.rhcloud.com/
http://comm-jfiala.rhcloud.com/sig/OpenshiftEDU.html

**Comment by dmueller2001** [comment]
This looks fine to me! Can you push it live today?

**Comment by jsvgoncalves** [comment]
@dmueller2001 the changes were already pushed, as we have automatic deployments.
