### ISSUE TITLE
add a Image Buiders SIG page with link to sign-up to Commons Site

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#247]
proposed url: http://commons.openshift.org/sig/OpenshiftImageBuilders.html

links added to http://commons.openshift.org/index.html#interests section of home page

update google spreadsheet-based form to start collecting email addresses

@jiri-fiala @jsvgoncalves

**Comment by jiri-fiala** [comment]
@dmueller2001, could you please specify the form and the content of this new page?

**Comment by dmueller2001** [comment]
Form/Style should mirror the existing SIG page  /sig/Openshiftv3.html

Content for link on index.html: 

'OpenShift Image Builders' 

Content for beneath link on #interests section of index.html 

'Discuss, develop and disseminate best practices for building and maintaining Images for use with OpenShift'

Content for http://commons.openshift.org/sig/OpenshiftImageBuilders.html

'Join the OpenShift Image Builders Special Interest Group'

Cut the section of the page entitled 'OpenShift 3 Commons Briefings' on the .edu sig landing page.

Copy the section of the page entitled 'OpenShift 3 Articles' onto the ImageBuilders sig landing page.

**Comment by jiri-fiala** [comment]
Pages are prepared, forms pending - waiting for access.

**Comment by jiri-fiala** [comment]
This can be previewed & tested at:
http://comm-jfiala.rhcloud.com/
http://comm-jfiala.rhcloud.com/sig/OpenshiftEDU.html

**Comment by dmueller2001** [comment]
@jiri-fiala page looks good to me, can you push it live today?

**Comment by dmueller2001** [comment]
@jiri-fiala this looks good to me, many thanks Can you push it live today?

**Comment by jsvgoncalves** [comment]
@dmueller2001 the changes were already pushed, as we have automatic deployments.
