### ISSUE TITLE
add Apica to OpenShift Commons

### ISSUE THREAD

**Issue by getmakered** [openshift/commons.openshift.org#248]
url: https://www.apicasystem.com/

logo: https://www.apicasystem.com/apica-wp/wp-content/themes/apica-1.2/img/logo.png 

^^ is white on white so won't work..asking for a better one now..

**Comment by dmueller2001** [comment]
use this logo: https://www.apicasystem.com/wp-content/uploads/2014/04/264x91xcopy-ApicaLogo.png.pagespeed.ic_.YAMOsBDaw9.png

@jiri-fiala @jsvgoncalves
