### ISSUE TITLE
Enhance sign up forms

### ISSUE THREAD

**Issue by jiri-fiala** [openshift/commons.openshift.org#251]
Use AJAX to send the forms and check for Google Forms response, displaying appropriate messages to submitter, maybe skipping the `formsubmit.html` completely. This saves some redirecting time and provides better feedback.
Some forms (input fields & buttons) can be graphically tuned to be more in line with the main sign up form on homepage.

**Comment by jsvgoncalves** [comment]
Also, add proper validation of email addresses.

**Comment by dmueller2001** [comment]
@jiri-fiala @jsvgoncalves @developercorey 

Perhaps now is the time to try integrating with infusionsoft and adding a bit of automation into the processes? @developercorey has the details from prior conversations

**Comment by coreydaley** [comment]
Please re-open issue if this is still needed.  Hasn't been updated in 4+ months.
