### ISSUE TITLE
Briefings Calendar not showing (again)

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#258]
@jiri-fiala @developercorey 

the source looks good to me here:

commons.openshift.org/source/briefings.html.erb 

but the calendar widget is not showing on the live site for the /briefings.html page

**Comment by jsvgoncalves** [comment]
@dmueller2001 I can see it on the page, check the screenshot: 
![calendar](https://cloud.githubusercontent.com/assets/1872444/14679234/408283c0-0719-11e6-9cbb-92580873f959.png)

**Comment by developercorey** [comment]
@dmueller2001 it's the same issue as before with mixed content being blocked by firefox (and other browsers) due to the time.ly code.  You will need to take it up with them.

![2016-04-20-11 38](https://cloud.githubusercontent.com/assets/5060301/14680811/9d9e49ea-06ec-11e6-92c5-a7cfd51535b6.png)

**Comment by dmueller2001** [comment]
@jiri-fiala  fyi:
https does not show
http does

I'll call the time.ly folks again..

**Comment by dmueller2001** [comment]
issue was on time.ly's side (again); it has been resolved
