### ISSUE TITLE
add coscale to openshift commons

### ISSUE THREAD

**Issue by getmakered** [openshift/commons.openshift.org#280]
url: http://www.coscale.com
logo: http://cdn2.hubspot.net/hub/446547/file-2475383912-png/Blog_Pictures/2015_02/logo_with_title_-_black_-_622x300_(1).png

**Comment by dmueller2001** [comment]
@jiri-fiala I added that with my 'other' github account..

url: http://www.coscale.com
logo: http://cdn2.hubspot.net/hub/446547/file-2475383912-png/Blog_Pictures/2015_02/logo_with_title_-_black_-_622x300_(1).png
