### ISSUE TITLE
add a SIG page for OpenShift MSFT .Net

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#283]
add a link on http://commons.openshift.org/index.html#interests

using:
Title: OpenShift .Net 
Desc: Discuss, develop and disseminate best practices for developing and deploying .Net Apps and SQLServer on OpenShift.

add new landing page for OpenShift .New and form to collect interested participants.

using 

Title: .Net on OpenShift

Description: 
The principal purpose of the .Net Special Interest Group is to discuss, develop and disseminate best practices for developing  with .Net Applications, supporting SQL Server and using Visual Studio IDE with OpenShift.

**Comment by dmueller2001** [comment]
Please use the following 3 articles on the landing page as teasers for .Net community

https://blog.openshift.com/click2clouds-docker-container-kubernetes-based-visual-studio-2015-extension/
https://blog.openshift.com/get-true-devops-with-one-click-container-deployment-in-openshift-enterprise-3-with-click2cloud/
https://blog.openshift.com/openshift-commons-briefing-34-getupclouds-journey-microsoft-azure-openshift/

**Comment by jiri-fiala** [comment]
@dmueller2001, what about feeding all recent [blog posts tagged 'Microsoft'](https://blog.openshift.com/tag/microsoft/), instead of the three hard-coded articles? (The tag contains all the articles you have mentioned.)

**Comment by dmueller2001** [comment]
@jiri-fiala that would be fine, I will make sure those three are tagged properly

can you get this done by Monday?

Diane

**Comment by jiri-fiala** [comment]
@dmueller2001, this is published; form submissions are to be found in the '.NET' sheet.
