### ISSUE TITLE
add blog link to .NET SIG landing page 

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#291]
add this new .Net related link as the first one to this page: http://commons.openshift.org/sig/Openshift.NET.html

here's the blog post:

http://developers.redhat.com/blog/2016/06/16/simplifying-asp-net-applications-on-openshift-with-the-asp-net-core-s2i-builder/

**Comment by corey112358** [comment]
Articles on http://commons.openshift.org/sig/Openshift.NET.html are automatically pulled from the feed at https://blog.openshift.com/tag/microsoft/feed/, they are not manually added.  The best way to get that information listed there would be to write a blog on blog.openshift.com and tag it with microsoft.
