### ISSUE TITLE
update the commons.openshift.org landing page with Gathering section

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#311]
In a Section of the index.html page for commons.openshift.org, we need to promote and link to the Nov 7th event in Seattle (OpenShift Commons Gathering) http://openshiftgathering.com/openshiftgathering

This new Section should be a temporary first section of the page and be placed just below the header & nav bar, keeping all the existing sections but just moving them down one.

The section should include a call to action button that links to http://openshiftgathering.com/openshiftgathering 

I am open to design proposals; the content should mirror that found on the gathering landing page; however both pages use the same header graphic so there needs to be some thinking as to how to make this section look distinct from the header on the main page.

**Comment by developercorey** [comment]
How does this look?
https://www.dropbox.com/s/u8zwk0ca9vz14qm/2016-09-13-14%3A08.png?dl=0

**Comment by dmueller2001** [comment]
![mockuphomepage](https://cloud.githubusercontent.com/assets/4029488/18485943/cfad5136-79a3-11e6-9951-4c9f4acd2a1e.png)

Looks great but needs a call to action link to register today and a link to schedule (see mockup edited attached)

Can we add 2 links in Red as shown but in the same font & size as the When/Where

Schedule/Speakers -> https://meeting-reg.com/redhat/2016/public/openshiftgathering#schedule
Register ->https://www.eventbrite.com/e/openshift-commons-gathering-tickets-26815781725?aff=#tickets

**Comment by developercorey** [comment]
Updated Screenshot: https://www.dropbox.com/s/rz6hphnay174y81/2016-09-13-14%3A35.png?dl=0

**Comment by dmueller2001** [comment]
Can you also add the 3 person shadow watermark image from the #join sections background  into this section just on the opposite side from where it is used in the join section see:
![screen shot 2016-09-13 at 2 22 29 pm](https://cloud.githubusercontent.com/assets/4029488/18492864/632113e4-79c2-11e6-97f8-f9a789d96b95.png)

**Comment by developercorey** [comment]
Image added, new section has been deployed to production.

**Comment by dmueller2001** [comment]
you rock!
