### ISSUE TITLE
add jfrog to openshift commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#338]
url: https://www.jfrog.com
logo: http://bit.ly/2fRghaT

**Comment by wgordon17** [comment]
@dmueller2001 It would appear that your bit.ly link redirects to a private google map. Could you please provide the link to a publically available logo? Thank you

**Comment by dmueller2001** [comment]
logo: http://photos.prnewswire.com/prn/20141103/714835-a
