### ISSUE TITLE
landing page for gathering videos from Seattle OpenShift Commons Gathering

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#340]
![mock-up for gathering videos landing page](https://cloud.githubusercontent.com/assets/4029488/20634494/b6786f1a-b31f-11e6-9acb-bc0a65dfa01e.png)
Create a page https://commons.openshift.org/gathering/videos

similar to the layout here: https://www.openstack.org/videos/search?search=red%20hat

using all the videos in the /gathering playlist here:

https://www.youtube.com/playlist?list=PLaR6Rq6Z4Iqfahozh6X_RJwGYx0i94qXc

in the order that they occurred in the actual event's agenda here:

https://commons.openshift.org/gathering

@wgordon17 @jiri-fiala @jsvgoncalves

**Comment by dmueller2001** [comment]
Need to create a page that will allow us to post future gathering videos easily. We have 3 more gatherings planned for 2017 (Berlin, Boston and Austin) so this page will be getting additional content on a regular cadence. All of the videos will be edited and uploaded to the openshift youtube account.

There will be another /gathering page updated for each new event managed by Marketing Matters here: 
https://meeting-reg.com/redhat/2016/public/openshiftgathering

and there will be an eventbrite page for managing registrations for each gathering.

"Gatherings" should be added back into the main navigation bar immediately and continue link to https://meeting-reg.com/redhat/2016/public/openshiftgathering until the new site is launched.

Diane

**Comment by jiri-fiala** [comment]
Hi @dmueller2001, 
Please let me know if [**this**](http://comm-jfiala.rhcloud.com/videos.html) looks fine.

- I have mostly copied titles and descriptions from the videos on YouTube, with slight edits here and there. Please check that all the titles and descriptions are fine.
- There is also [the commons briefing #50 video](https://www.youtube.com/watch?v=cgF9NWNLM0U) in the playlist, that is on the last position; other videos are in chronological order per [the Gathering schedule](https://meeting-reg.com/redhat/2016/public/openshiftgathering#schedule), as requested.
- The "Videos" page is in the document root (videos.html), but there are rewrite rules that will take care of /gathering/videos and /videos requests.

**Comment by dmueller2001** [comment]
just remove the "OpenShift Commons Briefing #50: OpenShift Origin Overview & 1.3 Update" aka #50 

can you add a drop down from the nav bar on the home page for the videos so that there is a path to this page and to the event landing page? 

                   Gathering>Events goes to ->https://commons.openshift.org/gathering
                   Gathering>Videos goes to ->https://commons.openshift.org//gathering/videos

@jiri-fiala

**Comment by jiri-fiala** [comment]
Hi @dmueller2001,
[The preview](http://comm-jfiala.rhcloud.com/videos.html) has been updated.

Aside of the above requested, the video page is now downloading only video thumbnails and replace it with the youtube player iframe only after clicking the thumbnail, resulting in much better page download time.

**Comment by jiri-fiala** [comment]
@dmueller2001, could you please confirm this ^ is fine and we can publish?

**Comment by dmueller2001** [comment]
please add all the Berlin OpenShift Commons Gathering Videos ASAP to the videos page!

Here's the list: https://www.youtube.com/playlist?list=PLaR6Rq6Z4IqdHztUG96ldb6B6h-BuuQud

@jiri-fiala @jsvgoncalves

**Comment by jiri-fiala** [comment]
@dmueller2001 , the Berlin gathering videos will be tracked in issue #406.
For future reference, please make sure to open new issues for content updates.
Thank you.
