### ISSUE TITLE
add gathering(s) link back into the main navigation bar

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#341]
url://https://commons.openshift.org/gathering

link to the gathering page was dropped from the main navigation bar on the site; needs to be added back in and to have and "s" added to it.

Should read "gatherings" 

as we are going to do 3 more in 2017 (Berlin, Boston, Austin) and want to leave a trail of cookies to the past event

@wgordon17

**Comment by wgordon17** [comment]
Would you like the URL to be updated to include the "s", or just the navigation button?

**Comment by dmueller2001** [comment]
Just the navigation not the URL

Thanks

Diane
