### ISSUE TITLE
add rohlik.cz to Openshift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#342]
url: rohlik.cz
logo: 
![rohlik](https://cloud.githubusercontent.com/assets/4029488/20685048/bce2dc24-b580-11e6-98e8-e55bcaa24fd0.png)

@wgordon17

**Comment by wgordon17** [comment]
Is there a link URL to the logo, or should I utilize the provided screenshot?

**Comment by dmueller2001** [comment]
Use the .PNG that was supplies
