### ISSUE TITLE
Replace th kinvolk logo with SVG

### ISSUE THREAD

**Issue by wgordon17** [openshift/commons.openshift.org#357]
Can you replace the pixelated kinvolk logo on the commons site with this svg file

[kinvolk_logo.svg.zip](https://github.com/openshift/commons.openshift.org/files/697326/kinvolk_logo.svg.zip)

**Comment by wgordon17** [comment]
Adding @dmueller2001 for visibility

**Comment by wgordon17** [comment]
@jiri-fiala 

Checkout my version of this at https://github.com/wgordon17/commons.openshift.org/tree/replace-kinvolk-logo

Deploying it locally only shows an empty spot for the logo, and inspecting it further shows the logo is available, but showing at 0x0 pixels.

**Comment by jiri-fiala** [comment]
@wgordon17, try adding widht and heigh attributes to the svg file, the same as the other svgs we have there, i.e.:
`<svg id="svg4329" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1337.9" height="832" viewBox="0 0 1337.9 832">...`
