### ISSUE TITLE
replace the posterboard style calendar with a monthly style calendar on the briefings.html page

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#363]
Paste this code into page:

<script class="ai1ec-widget-placeholder" data-widget="ai1ec_superwidget" data-action="month">
  (function(){var d=document,s=d.createElement('script'),
  i='ai1ec-script';if(d.getElementById(i))return;s.async=1;
  s.id=i;s.src='//live-timely-objzoywz.time.ly/?ai1ec_js_widget';
  d.getElementsByTagName('head')[0].appendChild(s);})();
</script>

replacing the poster board widget

@wgordon17

**Comment by jiri-fiala** [comment]
Closed by #364
