### ISSUE TITLE
add boston summit gathering to site navigation

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#390]
![screen shot 2017-03-08 at 11 18 52 am](https://cloud.githubusercontent.com/assets/4029488/23719723/5bc92924-03f1-11e7-8ee2-dd3340c11fea.png)

Currently the Upcoming Events under the Navigation goes directly to the 'Berlin' event landing page

We need to add in the landing page for the 'Boston' gathering so we can start promoting registration now

See the picture for my suggested change to the nav menu for this drop down
This is the url to the new Boston landing page:
http://openshiftgathering.com/openshiftgathering/boston

**Comment by jsvgoncalves** [comment]
@dmueller2001 caring about mobile devices and usability here, I propose something like this instead:
![commonsgather](https://cloud.githubusercontent.com/assets/1872444/23744485/ae90dc24-04b4-11e7-9bd3-40ecc5586e8f.png)

**Comment by wgordon17** [comment]
+1 @jsvgoncalves 

I will move forward with implementing the less nested option

**Comment by wgordon17** [comment]
@dmueller2001 How do you feel about:

![screen shot 2017-03-09 at 14 03 21](https://cloud.githubusercontent.com/assets/22222756/23766000/3432605c-04d1-11e7-94d8-c035f3eaa4c5.png)

**Comment by wgordon17** [comment]
@dmueller2001 Mobile nav layout:

![screen shot 2017-03-09 at 14 06 09](https://cloud.githubusercontent.com/assets/22222756/23766125/9891a13e-04d1-11e7-8082-7fe11e4607f3.png)

**Comment by dmueller2001** [comment]
"Berlin Gathering Mar 28" is better thatn "Berlin Event - Mar 28"

**Comment by wgordon17** [comment]
I was thinking "Berling Gathering - Mar 28" was a little redundant given that it's nested under "Gatherings" in desktop view. The nesting isn't available on mobile, which is why I added "Gathering" there.

I could just remove "Event" on desktop...or I could replace with "Gathering". Whatever you prefer =)

**Comment by dmueller2001** [comment]
on Desktop

Berlin - March 28
Boston - May 1

on Mobile 

Berlin Gathering Mar 28
Boston Gathering May 1
