### ISSUE TITLE
section change request on index.html

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#420]
Please swap the "Find Your Commonality" Section with the "Commons Participants" section on http://commons.openshift.org/index.html

You may want to review & suggest a UX Design change for the "Commons Participants" section to make it more navigable/searchable as there are now 250+ logos

**Comment by jiri-fiala** [comment]
The logo area redesign is separated from this issue into #424. @dmueller2001, please feel free to comment there.
