### ISSUE TITLE
add the Boston Gathering Summit to the videos.html

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#421]
All 14 videos from the May 1 OpenShift Commons Gathering are now up on our youtube channel here:
https://www.youtube.com/playlist?list=PLaR6Rq6Z4IqdDQ3prS7Ef91DeL1cu6Yqq

Please add them to:
http://commons.openshift.org/videos.html

You may need to reconsider the organization of the page to make the navigation/search more useable.

**Comment by jiri-fiala** [comment]
Separating videos into categories is going to be tracked in #410
