### ISSUE TITLE
revamp the participants' logos area

### ISSUE THREAD

**Issue by jiri-fiala** [openshift/commons.openshift.org#424]
This issue is based on @dmueller2001's comment in issue #420 
*"You may want to review & suggest a UX Design change for the "Commons Participants" section to make it more navigable/searchable as there are now 250+ logos"*

-------
Currently, all the available logos are displayed in alphabetical order and searchable (by company name) on both the [index page](http://commons.openshift.org/index.html#colleagues) and the [participant search page](http://commons.openshift.org/participants.html).

I would suggest, a few participant logos on a rotating "carousel" to be displayed (e.g. a single row of 5 logos for desktop-sized viewports), rotated every few seconds. The whole participant list is still to be available and searchable.
This does not exactly improve navigability and searchability, but I think the current name search is sufficient and we are going to avoid the "wallpaper" style of displayed logos that is cluttering the page and reducing the load time, while still presenting there are a lot of participants by rotating the logos.

**Comment by dmueller2001** [comment]
Can you make the selection of the participant logos in the rotating carousel automated and randomize it? or do I need to make a selection of logos for the carousel? I'd rather the random selection as then it wouldn't look like I was favoring any one member organization..

**Comment by jiri-fiala** [comment]
Random order seems fair to me, we'll look into it.

**Comment by jiri-fiala** [comment]
@dmueller2001, please have a look on [**this draft**](http://stage2-jfiala.rhcloud.com/#colleagues) and approve or comment.

- Logos are still clickable, the blurry zoom effect is removed.
- The link to the full participant list now reports the total number of commons participants (per the yaml source file).
- The logos' order is randomized on site build, so page refresh won't shuffle them. With any change of the site, including new logo additions, the order is reshuffled.
- All the logos are in the carousel, i.e. this change does not reduce the downloaded data amount, but also means we're not favoring anyone in particular.
- On smaller viewports, there are always 5 logo per slice, only stacked vertically.

**Comment by dmueller2001** [comment]
This revised design looks good. Please push it live as soon as you are
ready.
