### ISSUE TITLE
Redis Labs logo to be added to site

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#44]
logo emailed to edirst

link to https://redislabs.com

**Comment by EmilyDirsh** [comment]
@dmueller2001 I don't see this logo in my email - if you can send it again, I'll add it. Thanks.

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/cb8b8eecfa2961219dbd6cafa860baca4809eea5
