### ISSUE TITLE
add lzlabs to Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#444]
url: https://www.lzlabs.com
logo: https://www.lzlabs.com/wp-content/uploads/2016/08/lzlabs-logo-tagline-300x254.png

**Comment by wgordon17** [comment]
@dmueller2001 Jiri has removed the "software defined mainframe ®" tag line in #445 to make the logo fit properly on our site. Is this acceptable? Additionally, they have a nice horizontal logo (https://lzlabs.wpengine.com/wp-content/uploads/2016/09/lzlabs-logo-header-155x70_clear.png) that may work better overall.

Please advise.

**Comment by dmueller2001** [comment]
use this one: https://lzlabs.wpengine.com/wp-content/uploads/2016/09/lzlabs-logo-header-155x70_clear.png

**Comment by jiri-fiala** [comment]
The LzLabs logo has been replaced with the above linked [horizontal variant](https://github.com/openshift/commons.openshift.org/pull/445/files).
