### ISSUE TITLE
Targeting ".active" videos?

### ISSUE THREAD

**Issue by wgordon17** [openshift/commons.openshift.org#446]
Hey @jiri-fiala,

Why are you targeting on videos with the ".active" class in https://github.com/openshift/commons.openshift.org/blob/master/source/videos.html.erb#L57?

In some other testing I was doing, the ".active" class caused the height matching not to work until I removed it.

**Comment by wgordon17** [comment]
Actually, I think I figured it out...the ".active" class is used for categories, but un-categorized videos, i.e., no tabs, will end up not having their height adjusted.

**Comment by jiri-fiala** [comment]
Yes @wgordon17, this is for initial height matching of the active tab. Further tab switching and height adjustment is covered [here](https://github.com/openshift/commons.openshift.org/blob/master/source/_videos.erb#L59-L63).
When there are no bootstrab tabs in place, that css class selector shouldn't be used.

**Comment by jiri-fiala** [comment]
If there are no categorized videos, [tabs are never rendered](https://github.com/openshift/commons.openshift.org/blob/master/source/_videos.erb#L45-L50), so this option has to be reflected in the two jQuery selectors [here](https://github.com/openshift/commons.openshift.org/blob/master/source/videos.html.erb#L57-L58), to make this portable elsewhere.
