### ISSUE TITLE
add Bitnami to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#452]
url: https://bitnami.com/
logo: https://d33np9n32j53g7.cloudfront.net/assets/new/logo-a8f6bf1f06aa6acaf83d64142c4ec8cd.png

**Comment by jiri-fiala** [comment]
@dmueller2001, can you ask Bitnami to provide a logo with a transparent background? Bitnami does not offer that on [their logo page](https://bitnami.com/about-us/logos).
The white background does not look nice in the carousel section, other logos are with transparent background there.

**Comment by dmueller2001** [comment]
this one has a transparent background: 

https://bitnami.com/downloads/logos/bitnami.png
