### ISSUE TITLE
add massachusetts open cloud (MOC) to OpenShift Commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#473]
url:https://info.massopencloud.org
logo: https://info.massopencloud.org/wp-content/uploads/2016/09/large-logo-moc-300x215.jpg

**Comment by jiri-fiala** [comment]
[moc-T3.png](https://info.massopencloud.org/wp-content/uploads/2016/01/moc-T3.png) is going to be used as the logo, the suggested one is too large.

**Comment by wgordon17** [comment]
https://info.massopencloud.org/ causes an SSL error when browsing the site. It then redirects to https://massopen.cloud/ anyway. @dmueller2001, can we use the https://massopen.cloud/ URL instead?

**Comment by jiri-fiala** [comment]
We most likely want to change to URL, as the cert currently used on info.massopencloud.org is issued for massopen.cloud and *.massopen.cloud, so I have force pushed the fix into the original branch...
