### ISSUE TITLE
regen the machine learning sig page 

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#548]
regen so that the newly tagged machine-learning blog posts will get picked up and displayed on the ml sig landing page..

http://commons.openshift.org/sig/OpenshiftMachineLearning.html

can you explain the ordering logic for the way the blog posts are listed on the landing page for the SIG? is it oldest first? most recently edited? which date field are you using to set the order of appearance of the blog posts on the landing page?

@jiri-fiala @wgordon17

**Comment by jiri-fiala** [comment]
The [blog rss feed](https://blog.openshift.com/tag/machine-learning/feed/) is processed at Middleman build time as the Google Feed API [currently used for dynamic retrieval](https://github.com/openshift/commons.openshift.org/blob/master/source/sig/_ml_articles.erb#L16) is not available [anymore](https://developers.google.com/feed/). The feed is going to be (again) dynamically fetched to remove this limitation; this is going to be tracked in issue #547 

Only the `pubDate` is available for each post in [the RSS feed](https://blog.openshift.com/tag/machine-learning/feed/). We do not do explicit ordering atm, the articles are ordered by `pubDate` (newest first) in the feed already; only [first ten](https://github.com/openshift/commons.openshift.org/blob/master/source/sig/_ml_articles.erb#L39) are fetched - i.e. up to 10 most recent articles tagged `machine-learning` available at build time.

**Comment by jiri-fiala** [comment]
The re-build is completed and deployed, recent articles are [fetched](http://commons.openshift.org/sig/OpenshiftMachineLearning.html) now.
