### ISSUE TITLE
add co-chairs names to ML SIG Landing page

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#551]
text to be added:

"Machine Learning on OpenShift SIG Co-chairs: 
Matthew Farrellee (Red Hat) and David Aronchick (Google)"

image for location of text:
![addco-chairstomlsiglandingpage](https://user-images.githubusercontent.com/4029488/33445268-457d39b6-d5b1-11e7-92fe-ea2e30604d65.png)
@wgordon17 @jiri-fiala

**Comment by jiri-fiala** [comment]
@dmueller2001, the text seems to repeat most of the header above; what do you think about a [this shortened version](http://comm-jfiala.rhcloud.com/sig/OpenshiftMachineLearning.html)?

**Comment by dmueller2001** [comment]
+1 on the shortened version, it is much better.. thanks
