### ISSUE TITLE
add forsythe logo

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#69]
logo sent to edirsh

http://www.forsythe.com/

**Comment by EmilyDirsh** [comment]
@dmueller2001 I have the synnefo logo, but not the forsythe logo

**Comment by dmueller2001** [comment]
here's the logo: http://upload.wikimedia.org/wikipedia/en/6/65/Forsythe_Logo.png

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/d7ab7e60e44735c169313307265e3f3f73739df7
