### ISSUE TITLE
add DWP/UK Gov logo

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#72]
still need to get the logo to edirsh

url: https://www.gov.uk/government/organisations/department-for-work-pensions

**Comment by dmueller2001** [comment]
emailed DWP logo to edirsh

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/1cf5b7643bf0f91508e4bd060c4f289375417c2d
