### ISSUE TITLE
StartApp.bg logo

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#82]
image:
http://www.startapp.bg/assets/img/startapp.png

url:
http://www.startapp.bg

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/9a962dcd9c278570a5fff58c353707fe05916952

**Comment by dmueller2001** [comment]
StartApp.BG is now http://blog.cloudstrap.io/startapp-bg-stava-cloudstrap-io/

please update using this url: http://blog.cloudstrap.io/startapp-bg-stava-cloudstrap-io/

and this url: http://blog.cloudstrap.io/content/images/2015/10/cover-4.png

@jiri-fiala @jsvgoncalves

**Comment by jiri-fiala** [comment]
As [the blog post](http://blog.cloudstrap.io/startapp-bg-stava-cloudstrap-io/) will get outdated relatively soon, I would suggest to link the logo to [the Cloudstrap homepage](http://www.cloudstrap.io). Also, the [provided logo](http://blog.cloudstrap.io/content/images/2015/10/cover-4.png) is larger that we usually have, so it would be difficult to read when resized to the standard 120px width for commons participants. To keep the page consistent, I suggest updating the content as per [this commit](https://github.com/jiri-fiala/commons.openshift.org/commit/06d7a55d3a35370e0ff4287781e9cc81e1ebbe6e).

@dmueller2001, please preview the change [**here**](http://comm-jfiala.rhcloud.com/) and confirm this is ok to be merged and published. Thank you.

**Comment by dmueller2001** [comment]
@jiri-fiala yes, your suggestions are correct, i confirm these changes are ok
