### ISSUE TITLE
add Fairfield University to commons participant list

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#93]
url: www.fairfield.edu
logo: requested

**Comment by dmueller2001** [comment]
link to image: http://upload.wikimedia.org/wikipedia/en/c/c7/Fairfield_University.svg

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/69cd4ab8475c5e6b30c02f3303b90e84bd9c308e
