### ISSUE TITLE
Add thetis-apps to the commons participants list

### ISSUE THREAD

**Issue by dmueller2001** [openshift/commons.openshift.org#98]
url: http://www.thetis-apps.dk/

logo: http://static.wixstatic.com/media/2d48cc_1e6c4be3c80545c18d9d80c61584150b.png_srz_p_201_34_75_22_0.50_1.20_0.00_png_srz 
(i asked for a better one)

**Comment by EmilyDirsh** [comment]
Added in https://github.com/openshift/commons.openshift.org/commit/d7ab7e60e44735c169313307265e3f3f73739df7
